### PR TITLE
Global Error Handling

### PR DESCRIPTION
**Pull request by brunobord**
- [x] define the way errors are handled in the core module, use the right format that could be processed by the front-end the easiest way (send a message using a simple structure + throwing the HTTP status header looks like the best candidate)
- [x] tests for all the core variants,
- [x] amend documentation accordingly,
- [x] Demo views

### CODE REVIEW

**Review by rodo — APPROVED** [review]

**Review by wo0dyn — APPROVED** [review]
I didn't spot any issue. LGTM! Thank you for your work.

**Comment by brunobord** [comment]
added a demo view. @amessinger do you think it's worth modifiying the JS bit to redirect the AJAX calls that trigger an error to console.error() or send a message to the user a different way? (as an example)

**Comment by amessinger** [comment]
I guess that displaying errors as a `<ul><li>{error message}</li></ul>` beneath the input would be enough.

**Comment by brunobord** [comment]
> I guess that displaying errors as a `<ul><li>{error message}</li></ul>` beneath the input would be enough.

hem. they're returned in the JSON payload after the AJAX call, so it'd be a (minor?) modification in the .js file(s)

**Comment by amessinger** [comment]
Minor indeed. We could introduce a new "selectize-errors.js" file, with a modified 

```
error: function(data) {
  // let's loop through data and insert list elements
  callback();
},
```

**Pull request merged**
