### PR TITLE
Fix ImportError for AppConfig

### PR DESCRIPTION
**Pull request by FlogFr**

### CODE REVIEW

**Comment by brunobord** [comment]
care to explain?

**Comment by FlogFr** [comment]
You can now in Django configure your applications with the AppConfig.
In the installed apps, you can config the application as so:
'super_path.apps.SuperAppConfig'

This leads to wrong import cause the code was based only on the path of the name of the application. There won't be any 'super_path.apps.SuperAppConfig.agnocomplete' module.

**Comment by FlogFr** [comment]
Little update, this could be nice to be future proof of every app_config possible :)

**Comment by brunobord** [comment]
My main issue with this patch is that if at some point an `application.autocomplete` module raises a **true** ImportError (typo in the module name, whatever) this import error will be explicitely silent and very hard to debug.

**Comment by FlogFr** [comment]
need to think of another way then

**Comment by wo0dyn** [comment]
Is this PR still WiP?

**Comment by FlogFr** [comment]
This PR is reviewable / discussable.
It addresses the problem to import django application through AppConfig and not through only python path.

**Pull request closed without merging**
