### PR TITLE
Attempt to make it installable with Django 3.X serie

### LINKED ISSUE #119: Add support for Django 3.0 and 3.1
Even if we don't use those internally yet :)

### PR DESCRIPTION
**Pull request by yohanboniface**
Maybe a bit naive, but:

- works with uMap running Django 3.2
- django-agnocomplete tests passe

I'm not in Django stuffs since a long time, so I may be missing something, but here is a starting point :)

fix https://github.com/peopledoc/django-agnocomplete/issues/119

### CODE REVIEW

**Comment by ewjoachim** [comment]
Wow, I didn't watch the repo and consequently didn't see this PR .Sorry about that. With the upcoming deprecation of Django 2.2, we'll soon be upgrading this lib to 3.2. Thanks for you work on that, I'll see if we can get someone to merge it in the coming... weeks probably ? :sweat_smile:

**Review by ewjoachim — APPROVED** [review]

**Review by mike-perdide — APPROVED** [review]
Looks good to me!

**Comment by ewjoachim** [comment]
We're going to work a bit on the lib following this, and we'll release shortly after :)

**Comment by ewjoachim** [comment]
@mike-perdide said he checked that it runs correctly, even if travis won't run :) That's enough for me ! Thank you @yohanboniface

**Comment by yohanboniface** [comment]
:tada: 

Entre-temps, Django 4.0 est sorti, j'avais commencé à regarder pour uMap, et j'avais ça comme diff en cours côté agnocomplete:

```diff
diff --git a/agnocomplete/core.py b/agnocomplete/core.py
index 4fbcd50..ffb5f4d 100644
--- a/agnocomplete/core.py
+++ b/agnocomplete/core.py
@@ -8,7 +8,7 @@ import logging
 
 from django.db.models import Q
 from django.core.exceptions import ImproperlyConfigured
-from django.utils.encoding import force_text as text
+from django.utils.encoding import force_str as text
 from django.conf import settings
 import requests
 
diff --git a/agnocomplete/urls.py b/agnocomplete/urls.py
index 25e9f6d..d88f8a4 100644
--- a/agnocomplete/urls.py
+++ b/agnocomplete/urls.py
@@ -1,7 +1,7 @@
 """
 Agnostic Autocomplete URLS
 """
-from django.conf.urls import re_path
+from django.urls import re_path
 from .views import AgnocompleteView, CatalogView
 
 urlpatterns = [
diff --git a/agnocomplete/views.py b/agnocomplete/views.py
index cdfcea3..ea0baca 100644
--- a/agnocomplete/views.py
+++ b/agnocomplete/views.py
@@ -5,7 +5,7 @@ from six import with_metaclass
 from abc import abstractmethod, ABCMeta
 from django.core.exceptions import PermissionDenied, SuspiciousOperation
 from django.http import Http404, JsonResponse
-from django.utils.encoding import force_text as text
+from django.utils.encoding import force_str as text
 from django.utils.functional import cached_property
 from django.views.generic import View
```

Je vous laisse ça là :)

**Comment by ewjoachim** [comment]
Yep, we'll probably add 4.0 in the same step ! thanks :)

**Pull request merged**
